spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: root1234!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  mvc:
    path match:
      matching-strategy: ant_path_matcher